import { StyleSheet } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

import { useDeviceDimensions } from '@hooks';

export const useStyles = () => {
  const insets = useSafeAreaInsets();
  const { moderateHeight, moderateWidth } = useDeviceDimensions();

  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#EAFBF1',
    },
    scrollView: {
      flex: 1,
    },
    content: {
      paddingHorizontal: moderateWidth(4.5),
      paddingTop: moderateHeight(1.25),
      paddingBottom: Math.max(insets.bottom, moderateHeight(2.5)),
    },
    topBar: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingTop: insets.top + moderateHeight(1.1),
      paddingHorizontal: moderateWidth(4.5),
    },
    iconButton: {
      maxWidth: 42,
      maxHeight: 42,
      borderWidth: 1,
      alignItems: 'center',
      borderColor: '#DDE8DF',
      width: moderateWidth(9),
      height: moderateWidth(9),
      justifyContent: 'center',
      borderRadius: moderateWidth(2.5),
      backgroundColor: 'rgba(255,255,255,0.92)',
      shadowColor: '#426D4A',
      shadowOpacity: 0.08,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 3 },
      elevation: 2,
    },
    hiddenIconButton: {
      opacity: 0,
    },

    brandLogo: {
      width: moderateWidth(40),
      height: moderateHeight(5),
    },

    heroSection: {
      width: '100%',
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: moderateHeight(1.1),
      marginBottom: moderateHeight(1.25),
    },
    heroOrbit: {
      width: moderateWidth(58),
      height: moderateWidth(58),
      alignItems: 'center',
      justifyContent: 'center',
    },
    heroGlow: {
      position: 'absolute',
      top: moderateWidth(3.25),
      left: moderateWidth(3.25),
      width: moderateWidth(51.5),
      height: moderateWidth(51.5),
      borderRadius: moderateWidth(25.75),
    },
    heroGlowFill: {
      width: '100%',
      height: '100%',
      borderRadius: moderateWidth(25.75),
    },
    heroEnergyRing: {
      position: 'absolute',
      top: 0,
      left: 0,
      width: moderateWidth(58),
      height: moderateWidth(58),
    },
    heroEnergyRingContent: {
      width: '100%',
      height: '100%',
    },
    heroCircle: {
      width: moderateWidth(48.5),
      height: moderateWidth(48.5),
      alignItems: 'center',
      borderWidth: 1,
      borderColor: '#E0E9E2',
      borderRadius: moderateWidth(24.25),
      backgroundColor: 'rgba(255,255,255,0.97)',
      shadowColor: '#256C38',
      shadowOpacity: 0.13,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 7 },
      elevation: 6,
    },
    heroStatusArea: {
      width: '100%',
      height: '47%',
      alignItems: 'center',
      justifyContent: 'flex-end',
      paddingHorizontal: moderateWidth(5),
      paddingBottom: moderateHeight(1.1),
    },
    heroEyebrow: {
      color: '#7A867D',
      fontSize: moderateHeight(1.05),
      lineHeight: moderateHeight(1.5),
      letterSpacing: 1.1,
      marginBottom: moderateHeight(0.45),
    },
    heroStatusText: {
      width: '100%',
      fontSize: moderateHeight(1.8),
      lineHeight: moderateHeight(2.4),
      letterSpacing: 0.25,
    },
    heroDivider: {
      width: '56%',
      height: 1,
      backgroundColor: '#E7ECE8',
    },
    heroAction: {
      width: '100%',
      height: '52%',
      alignItems: 'center',
      justifyContent: 'center',
      paddingBottom: moderateHeight(0.25),
    },
    heroActionDisabled: {
      opacity: 0.42,
    },
    heroActionPressed: {
      opacity: 0.72,
      transform: [{ scale: 0.97 }],
    },
    heroActionIcon: {
      width: moderateWidth(10),
      height: moderateWidth(10),
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: moderateWidth(5),
      marginBottom: moderateHeight(0.45),
    },
    heroActionSvg: {
      width: moderateWidth(5.2),
      height: moderateWidth(5.2),
    },
    heroActionLabel: {
      letterSpacing: 0.65,
      backgroundColor: '#DDF9E4',
      fontSize: moderateHeight(2),
      lineHeight: moderateHeight(2.5),
      borderRadius: moderateHeight(1.5),
      paddingHorizontal: moderateWidth(5),
      paddingVertical: moderateHeight(0.5),
    },
    heroParticle: {
      position: 'absolute',
      zIndex: 2,
      width: moderateWidth(1.8),
      height: moderateWidth(1.8),
      borderRadius: moderateWidth(0.9),
      shadowColor: '#20BE53',
      shadowOpacity: 0.5,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 0 },
      elevation: 3,
    },
    heroParticleOne: {
      top: moderateWidth(10),
      right: moderateWidth(4.5),
    },
    heroParticleTwo: {
      bottom: moderateWidth(9),
      left: moderateWidth(5),
      width: moderateWidth(1.3),
      height: moderateWidth(1.3),
      borderRadius: moderateWidth(0.65),
    },
    heroParticleThree: {
      top: moderateWidth(3),
      left: moderateWidth(18),
      width: moderateWidth(1.1),
      height: moderateWidth(1.1),
      borderRadius: moderateWidth(0.55),
    },

    heroSpace: {
      height: moderateHeight(4.5),
    },
    connectionPill: {
      borderWidth: 1,
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'flex-end',
      borderColor: '#D8E8DA',
      backgroundColor: 'rgba(255,255,255,0.78)',
      minHeight: moderateHeight(3.6),
      borderRadius: moderateWidth(5),
      marginBottom: moderateHeight(1.2),
      paddingHorizontal: moderateWidth(2.8),
      shadowColor: '#426D4A',
      shadowOpacity: 0.06,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
      elevation: 1,
    },
    connectionPillDisconnected: {
      backgroundColor: '#FFF7F7',
    },
    connectionDot: {
      width: moderateWidth(2.2),
      height: moderateWidth(2.2),
      borderRadius: moderateWidth(1.1),
      marginRight: moderateWidth(1.8),
      backgroundColor: '#31C44C',
    },
    connectionDotDisconnected: {
      backgroundColor: '#ED3237',
    },
    connectionText: {
      color: '#31C44C',
      fontSize: moderateHeight(1.4),
    },
    connectionTextDisconnected: {
      color: '#ED3237',
    },
    card: {
      width: '100%',
      borderWidth: 1,
      borderColor: '#DDE7DF',
      borderRadius: moderateWidth(5),
      backgroundColor: '#FFFFFF',
      marginBottom: moderateHeight(1.25),
      shadowColor: '#315B39',
      shadowOpacity: 0.09,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 4 },
      elevation: 3,
    },
    statusCardShadow: {
      width: '100%',
      minHeight: moderateHeight(9.4),
      borderRadius: moderateWidth(5),
      marginBottom: moderateHeight(1.25),
      shadowColor: '#18833A',
      shadowOpacity: 0.13,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 4 },
      elevation: 4,
    },
    statusCardShell: {
      flex: 1,
      overflow: 'hidden',
      borderRadius: moderateWidth(5),
      padding: moderateWidth(0.6),
    },
    statusCard: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      borderRadius: moderateWidth(4.4),
      backgroundColor: '#F9FFFA',
      paddingHorizontal: moderateWidth(3.6),
      paddingVertical: moderateHeight(1.25),
    },
    statusIconContainer: {
      width: moderateWidth(11),
      height: moderateWidth(11),
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: '#C8F1D1',
      borderRadius: moderateWidth(3.5),
      backgroundColor: '#E4FAE9',
    },
    statusIcon: {
      width: moderateWidth(6),
      height: moderateWidth(6),
    },
    statusCopy: {
      flex: 1,
      marginLeft: moderateWidth(3),
      marginRight: moderateWidth(2),
    },
    statusTitle: {
      color: '#31C44C',
      letterSpacing: 0.25,
      fontSize: moderateHeight(1.4),
      marginBottom: moderateHeight(0.3),
    },
    statusDescription: {
      color: '#18251B',
      fontSize: moderateHeight(1.65),
      lineHeight: moderateHeight(2.25),
    },
    statusIndicator: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#E3F9E8',
      borderRadius: moderateWidth(4),
      paddingHorizontal: moderateWidth(2),
      paddingVertical: moderateHeight(0.45),
    },
    statusIndicatorDisconnected: {
      backgroundColor: '#FFF0F0',
    },
    statusIndicatorDot: {
      width: moderateWidth(1.5),
      height: moderateWidth(1.5),
      borderRadius: moderateWidth(0.75),
      backgroundColor: '#31C44C',
      marginRight: moderateWidth(1.1),
    },
    statusIndicatorDotDisconnected: {
      backgroundColor: '#ED3237',
    },
    statusIndicatorText: {
      color: '#21843D',
      fontSize: moderateHeight(1.1),
      lineHeight: moderateHeight(1.6),
    },
    statusIndicatorTextDisconnected: {
      color: '#C52D32',
    },
    deviceInfoCard: {
      width: '100%',
      borderWidth: 1,
      borderColor: '#DDE7DF',
      borderRadius: moderateWidth(4),
      backgroundColor: '#FFFFFF',
      marginBottom: moderateHeight(1.25),
      paddingHorizontal: moderateWidth(3.4),
      paddingVertical: moderateHeight(1),
      shadowColor: '#315B39',
      shadowOpacity: 0.06,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 3 },
      elevation: 2,
    },
    deviceInfoHeader: {
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'center',
    },
    deviceInfoIcon: {
      flexShrink: 0,
      width: moderateWidth(8.8),
      height: moderateWidth(8.8),
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: moderateWidth(2.8),
      backgroundColor: '#E4FAE9',
      marginRight: moderateWidth(2.4),
    },
    deviceInfoIconSvg: {
      width: moderateWidth(5),
      height: moderateWidth(5),
    },
    deviceInfoCopy: {
      flex: 1,
      minWidth: 0,
    },
    deviceInfoName: {
      color: '#18251B',
      fontSize: moderateHeight(1.55),
      lineHeight: moderateHeight(2.1),
    },
    deviceInfoDetail: {
      color: '#667085',
      fontSize: moderateHeight(1.4),
      lineHeight: moderateHeight(1.8),
      marginTop: moderateHeight(0.15),
    },
    deviceInfoDetail2: {
      color: '#667085',
      marginTop: moderateHeight(0.5),
      fontSize: moderateHeight(1.4),
      lineHeight: moderateHeight(1.8),
    },
    deviceInfoLocation: {
      color: '#667085',
      fontSize: moderateHeight(1.6),
      lineHeight: moderateHeight(1.8),
      // marginTop: moderateHeight(0.7),
    },
    metricsCard: {
      paddingHorizontal: moderateWidth(3.2),
      paddingVertical: moderateHeight(1.4),
    },
    metricsGrid: {
      minHeight: moderateHeight(8.4),
      flexDirection: 'row',
      alignItems: 'stretch',
      columnGap: moderateWidth(1.5),
    },
    metric: {
      flex: 1,
      minWidth: 0,
      justifyContent: 'center',
      paddingHorizontal: moderateWidth(1.6),
      paddingVertical: moderateHeight(1),
      borderWidth: 1,
      borderColor: '#E1E8E3',
      borderRadius: moderateWidth(3.6),
      backgroundColor: '#F8FAF9',
    },
    metricHeader: {
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'center',
    },
    metricIconContainer: {
      flexShrink: 0,
      width: moderateWidth(6.6),
      height: moderateWidth(6.6),
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: moderateWidth(3.3),
      backgroundColor: '#DDF9E4',
      marginRight: moderateWidth(1),
    },
    metricIcon: {
      width: moderateWidth(3.8),
      height: moderateWidth(3.8),
    },
    metricLabel: {
      flexShrink: 1,
      color: '#667085',
      fontSize: moderateHeight(1.8),
      lineHeight: moderateHeight(2),
    },
    metricLabelSetCurrent: {
      flexShrink: 1,
      color: '#667085',
      fontSize: moderateHeight(1.6),
      lineHeight: moderateHeight(2),
    },
    metricValue: {
      color: '#101828',
      fontSize: moderateHeight(2.3),
      lineHeight: moderateHeight(3),
      letterSpacing: -0.3,
      marginTop: moderateHeight(0.7),
    },
    metricUnit: {
      color: '#667085',
      fontSize: moderateHeight(1.35),
    },
    phaseToggle: {
      borderTopWidth: 1,
      flexDirection: 'row',
      alignItems: 'center',
      borderTopColor: '#E7ECE8',
      marginTop: moderateHeight(1.4),
      justifyContent: 'space-between',
      paddingTop: moderateHeight(1.25),
      paddingHorizontal: moderateWidth(1),
    },
    phaseToggleLabel: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    phaseToggleIconContainer: {
      width: moderateWidth(8),
      height: moderateWidth(8),
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: moderateWidth(4),
      backgroundColor: '#F0F3F1',
    },
    phaseIcon: {
      width: moderateWidth(4.5),
      height: moderateWidth(4.5),
    },
    sectionTitle: {
      color: '#18201A',
      fontSize: moderateHeight(1.55),
      marginLeft: moderateWidth(2.2),
    },
    phaseChevronContainer: {
      width: moderateWidth(8),
      height: moderateWidth(8),
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: moderateWidth(4),
      backgroundColor: '#F0F3F1',
    },
    phaseToggleIconExpanded: {
      transform: [{ rotate: '180deg' }],
    },
    expandedPhaseSection: {
      rowGap: moderateHeight(1),
      paddingTop: moderateHeight(0.8),
    },
    phaseMetricCard: {
      borderRadius: moderateWidth(3),
    },
    phaseBadge: {
      maxWidth: 38,
      maxHeight: 38,
      alignItems: 'center',
      width: moderateWidth(8),
      height: moderateWidth(8),
      justifyContent: 'center',
      backgroundColor: '#EAFBF1',
      borderRadius: moderateWidth(2.3),
    },
    phaseBadgeText: {
      color: '#31C44C',
      fontSize: moderateHeight(1.8),
    },
    phaseCardTitle: {
      flex: 1,
      color: '#080808',
      fontSize: moderateHeight(1.85),
      marginLeft: moderateWidth(0.5),
    },
    phaseMetricGrid: {
      flexDirection: 'row',
      columnGap: moderateWidth(2.2),
    },
    phaseMiniMetric: {
      flex: 1,
      borderWidth: 1,
      borderColor: '#E1E8E3',
      justifyContent: 'center',
      backgroundColor: '#F8FAF9',
      minHeight: moderateHeight(5.8),
      borderRadius: moderateWidth(3),
      paddingHorizontal: moderateWidth(3),
    },
    phaseMiniLabel: {
      color: '#667085',
      fontSize: moderateHeight(1.3),
      marginBottom: moderateHeight(0.3),
    },
    phaseMiniValue: {
      color: '#101828',
      fontSize: moderateHeight(2),
      lineHeight: moderateHeight(2.6),
    },
    phaseMiniUnit: {
      fontSize: moderateHeight(1.35),
    },
    sessionCard: {
      flexDirection: 'row',
      alignItems: 'stretch',
      columnGap: moderateWidth(2),
      minHeight: moderateHeight(10.8),
      paddingVertical: moderateHeight(1.4),
      paddingHorizontal: moderateWidth(3.2),
    },
    currentControl: {
      paddingVertical: moderateHeight(0.8),
    },
    currentControlRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    currentArrowButton: {
      width: moderateWidth(8),
      height: moderateWidth(8),
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: moderateWidth(4),
      // backgroundColor: '#DDF9E4',
      // shadowColor: '#43B75C',
      // shadowOpacity: 0.1,
      // shadowRadius: 5,
      // shadowOffset: { width: 0, height: 2 },
      // elevation: 1,
    },
    currentArrowButtonDisabled: {
      opacity: 0.35,
    },
    currentArrowLeft: {
      transform: [{ rotate: '180deg' }],
    },
    currentValue: {
      minWidth: moderateWidth(13),
      color: '#101828',
      textAlign: 'center',
      fontSize: moderateHeight(2.3),
      lineHeight: moderateHeight(3),
      letterSpacing: -0.3,
      marginTop: moderateHeight(0.7),
    },
    currentUnit: {
      fontSize: moderateHeight(1.45),
    },
    swipeContainer: {
      minHeight: moderateHeight(7.6),
      marginBottom: moderateHeight(1.2),
    },
    swipeTrack: {
      flex: 1,
      borderWidth: 1,
      overflow: 'hidden',
      position: 'relative',
      borderColor: '#DCE8DF',
      justifyContent: 'center',
      backgroundColor: '#F9FFFA',
      borderRadius: moderateWidth(4.8),
      shadowColor: '#315B39',
      shadowOpacity: 0.08,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 3 },
      elevation: 2,
    },
    swipeTrackCharging: {
      borderColor: '#F0CCCC',
      backgroundColor: '#FFF9F9',
    },
    swipePrompt: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingLeft: moderateWidth(15),
      paddingRight: moderateWidth(4),
    },
    swipePromptCharging: {
      paddingLeft: moderateWidth(4),
      paddingRight: moderateWidth(15),
    },
    swipeArrows: {
      flexDirection: 'row',
      alignItems: 'center',
      marginRight: moderateWidth(2.3),
    },
    swipeArrowsCharging: {
      marginRight: 0,
      marginLeft: moderateWidth(2.3),
    },
    swipeArrowSpacing: {
      marginLeft: moderateWidth(1.3),
    },
    swipeArrowReverse: {
      transform: [{ rotate: '180deg' }],
    },
    swipeLabel: {
      color: '#424656',
      fontSize: moderateHeight(1.7),
      lineHeight: moderateHeight(2.5),
    },
    swipeHandle: {
      position: 'absolute',
      top: 0,
      left: 0,
      bottom: 0,

      overflow: 'hidden',
      alignItems: 'center',
      width: moderateWidth(16),
      justifyContent: 'center',
      // backgroundColor: '#10B8A3',
      borderRadius: moderateWidth(4.8),

      shadowColor: '#149C62',
      shadowOpacity: 0.3,
      shadowRadius: 12,
      shadowOffset: { width: 4, height: 0 },
      elevation: 5,
    },
    swipeHandleCharging: {
      backgroundColor: '#F42F35',
      shadowColor: '#F42F35',
    },
    controlDisabled: {
      opacity: 0.55,
    },
    connectionErrorCard: {
      width: '100%',
      padding: moderateWidth(4),
      borderWidth: 1,
      borderColor: '#F3C2C4',
      borderRadius: moderateWidth(4),
      backgroundColor: '#FFF7F7',
      marginBottom: moderateHeight(1),
    },
    connectionErrorText: {
      color: '#9F1D24',
      fontSize: moderateHeight(1.55),
      lineHeight: moderateHeight(2.2),
    },
    retryButton: {
      alignSelf: 'center',
      width: moderateWidth(36),
      height: moderateHeight(5),
      borderRadius: moderateWidth(2.5),
    },
    chargerErrorCard: {
      width: '100%',
      paddingHorizontal: moderateWidth(4),
      paddingVertical: moderateHeight(1.2),
      borderWidth: 1,
      borderColor: '#F4D38A',
      borderRadius: moderateWidth(4),
      backgroundColor: '#FFF9E8',
      marginBottom: moderateHeight(1),
    },
    chargerErrorTitle: {
      color: '#8A5A00',
      fontSize: moderateHeight(1.6),
      marginBottom: moderateHeight(0.3),
    },
    chargerErrorText: {
      color: '#6F4B0B',
      fontSize: moderateHeight(1.45),
      lineHeight: moderateHeight(2),
    },
    commandFeedback: {
      color: '#15803D',
      fontSize: moderateHeight(1.45),
      lineHeight: moderateHeight(2),
      marginTop: moderateHeight(1),
      paddingHorizontal: moderateWidth(4),
    },
    commandFeedbackError: {
      color: '#B4232A',
    },
  });
};

export default useStyles;
